name: Deploy MkDocs and build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Добавьте другие зависимости, если они есть

      # 4. Собираем сайт
      - name: Build MkDocs site
        run: mkdocs build

      # 5. Заливаем собранный сайт в ветку main
      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          cp -r site/* ./  # Переносим содержимое из site в корень
          rm -rf site
          git add .
          git commit -m "Deploy MkDocs site via GitHub Actions" || echo "No changes to commit"
          git push origin main 
